baseYRL = "/"

theme = "LoveIt"

defaultContentLanguage = "en"

themesDir = "../../HUGO/themes"

title = "Kutty Story"

enableRobotsTXT = true

enableEmoji = true

# Language parameters
[languages]
  [languages.en]
    weight = 1

    languageCode = "en"
    hasCJKlanguage = false
    paginate = 12
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

    # Menu config
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        
        name = "Posts"
        url = "/posts/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 2
        

[params]
  version = "0.2.X"
  defaultTheme = "auto"
  description = "A science outreach effort"
  keywords = ["Blog", "Science Communication", "Outreach"]
  dateFormat = "2006-01-02"
  
  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
    name = "Kutty Story"

  [params.footer]
    enable = true
    hugo = true
    copyright = true
    since = 2020
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  [params.section]
   paginate = 20
   dateFormat = "01-02"
   rss = 10
  [params.home]
    rss = 10
  [params.home.profile]
    enable = false
  [params.home.posts]
    enable = true
    paginate = 6
  [params.page]
    hiddenFromHomePage = false
    twemoji = false
    lightgallery = false
    ruby = false
    fraction = true
    fontawesome = true
    linkToMarkdown = false
    rssFullText = false
    [params.page.toc]
      enable = false
    [params.page.code]
      copy = true
      maxShownLines = 10
    [params.page.math]
      enable = false
    [params.page.mapbox]
      accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"

      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      navigation = true
      geolocate = false
      scale = true
      fullscreen = true
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Whatsapp = true
    [params.page.comment]
      enable = true
      [params.page.comment.disqus]
        enable = true
        shortname = "kutty-story"

  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1
  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "UA-165285623-2"
      anonymizeIP = true
      cookie = false

[author]
  name = "xxxx"
  email = ""
  link = ""

[Permalinks]
  posts = ":year/:month/:filename"
[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

